#!/bin/bash

# $1 => Process App
# $2 => Track Acronym
# $3 => Snapshot Name

# Extract .zip file generated by exporting the Process App
unzip -oq "$SCRIPTS_DIR/temp/$UNIQUE_FILE_NAME.zip" -d "$LOCAL_GITREPO/$p_app/"

# Create directory to extract the .twx contents
if [ ! -d "$LOCAL_GITREPO/$p_app"/export ]; then
    mkdir "$LOCAL_GITREPO/$p_app"/export
fi

# Extract .twx file too
unzip -oq "$LOCAL_GITREPO/$p_app"/export.twx -d "$LOCAL_GITREPO/$p_app"/export/

# Delete the twx file
rm -f "$LOCAL_GITREPO/$p_app"/export.twx